name: AWS ECR Deployment

on:
  push:
    branches:
      - main

jobs:
  aws_ecr:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to ECR
        id: deploy_to_ecr
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin 654654507153.dkr.ecr.us-east-1.amazonaws.com
          sudo docker pull httpd:latest
          sudo docker tag httpd 654654507153.dkr.ecr.us-east-1.amazonaws.com/surendra:${IMAGE_TAG}
          sudo docker push 654654507153.dkr.ecr.us-east-1.amazonaws.com/surendra:${IMAGE_TAG}
